/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
static yyconst short int yy_acclist[394] =
    {   0,
       90,   88,   89,   87,   88,   89,   87,   89,   71,   88,
       89,   88,   89,   71,   88,   89,   71,   88,   89,   88,
       89,   71,   88,   89,   71,   88,   89,   56,   88,   89,
       71,   88,   89,   82,   88,   89,   75,   88,   89,   80,
       88,   89,   85,   88,   89,   85,   88,   89,   85,   88,
       89,   85,   88,   89,   85,   88,   89,   85,   88,   89,
       85,   88,   89,   85,   88,   89,   85,   88,   89,   85,
       88,   89,   85,   88,   89,   85,   88,   89,   85,   88,
       89,   85,   88,   89,   85,   88,   89,   85,   88,   89,
       85,   88,   89,   85,   88,   89,   85,   88,   89,   85,

       88,   89,   71,   88,   89,   89,   83,   70,   68,   72,
       69,   84,   56,   59,   57,   58,   56,   74,   81,   76,
       77,   79,   85,   85,   85,   13,   85,   85,   85,    8,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   22,   85,    2,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   73,   68,   86,   84,   86,   84,   57,   58,   60,
       78,    1,   85,   85,   85,    6,   85,   18,   85,   85,
       85,   85,   85,   85,   53,   85,   85,   85,   85,   85,

       85,   40,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   20,   85,   19,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       17,   85,   85,   85,   85,   85,   85,   85,   85,   68,
       62,   61,   63,   29,   85,   85,   85,   36,   85,   85,
       85,   85,   85,   85,    5,   85,   85,   85,   45,   85,
       39,   85,   85,   85,   47,   85,   85,   85,   85,   11,
       85,    9,   85,   25,   85,   48,   85,   85,    3,   85,
       85,   85,   85,   85,   85,   85,   85,   28,   85,   41,
       85,   30,   85,   85,   85,   38,   85,   65,   85,   85,

       85,   37,   85,   85,   51,   85,   85,   85,   85,   16,
       85,   85,   85,   85,   85,   85,   67,   85,   85,   12,
       85,   50,   85,   85,   21,   85,   52,   85,    7,   85,
       27,   85,   85,   26,   85,   85,   85,   10,   85,   43,
       85,   85,   15,   85,   34,   85,   55,   85,   23,   85,
       85,   49,   85,   64,   46,   85,   85,   85,   85,    4,
       85,   33,   85,   85,   85,   14,   85,   42,   85,   85,
       85,   85,   35,   85,   85,   85,   85,   66,   85,   85,
       44,   85,   24,   85,   85,   31,   85,   85,   32,   85,
       85,   54,   85

    } ;

static yyconst short int yy_accept[325] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   14,   17,   20,   22,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   58,   61,   64,
       67,   70,   73,   76,   79,   82,   85,   88,   91,   94,
       97,  100,  103,  106,  107,  108,  108,  109,  110,  110,
      111,  111,  112,  113,  113,  113,  113,  113,  113,  114,
      115,  117,  118,  118,  118,  118,  118,  118,  118,  119,
      120,  121,  122,  123,  124,  125,  126,  128,  129,  130,
      132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
      142,  143,  144,  145,  146,  147,  148,  149,  150,  151,

      152,  153,  155,  157,  158,  159,  160,  161,  162,  163,
      164,  165,  166,  167,  168,  169,  170,  171,  172,  173,
      173,  173,  174,  174,  175,  175,  177,  177,  178,  178,
      178,  178,  180,  180,  180,  180,  181,  181,  181,  181,
      181,  181,  181,  182,  184,  185,  186,  188,  190,  191,
      192,  193,  194,  195,  197,  198,  199,  200,  201,  202,
      204,  205,  206,  207,  208,  209,  210,  211,  212,  213,
      214,  215,  216,  218,  220,  221,  222,  223,  224,  225,
      226,  227,  228,  229,  230,  231,  233,  234,  235,  236,
      237,  238,  239,  240,  240,  241,  241,  241,  242,  242,

      243,  244,  244,  244,  244,  244,  244,  244,  246,  247,
      248,  250,  251,  252,  253,  254,  255,  257,  258,  259,
      261,  263,  264,  265,  267,  268,  269,  270,  272,  274,
      276,  278,  279,  281,  282,  283,  284,  285,  286,  287,
      288,  290,  292,  294,  295,  296,  298,  300,  301,  302,
      304,  305,  307,  307,  307,  307,  307,  307,  307,  308,
      309,  310,  312,  313,  313,  314,  315,  316,  317,  319,
      320,  322,  324,  325,  327,  329,  331,  333,  334,  336,
      337,  338,  340,  342,  343,  345,  347,  347,  347,  347,
      349,  351,  352,  354,  355,  357,  358,  359,  360,  362,

      364,  365,  366,  368,  370,  371,  371,  372,  373,  375,
      376,  377,  378,  380,  381,  383,  385,  386,  388,  389,
      391,  392,  394,  394
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,    6,   11,    6,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   39,
        1,   21,    1,    6,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   39,    6,   48,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1
    } ;

static yyconst short int yy_base[336] =
    {   0,
        0,    0,    0,    0,    0,    0,  513,  514,  514,  514,
      493,   46,  514,  504,   67,   37,  495,   76,  490,   34,
      489,  488,   19,   35,   60,   67,   22,   61,  466,    0,
      469,  467,   68,   73,   72,  463,  471,   89,   90,   23,
      471,  473,  451,  514,  514,  119,  514,  493,  122,  514,
      125,  514,  514,  146,  115,  167,  188,  482,  188,   94,
      114,    0,  473,   50,  458,  173,  467,  466,  514,  472,
      514,  514,  514,    0,  119,  453,  465,  460,  452,    0,
      446,  443,  458,   95,  171,  443,  446,  441,  455,  446,
      445,  441,  440,  185,  445,  447,  149,  451,  427,  436,

      435,    0,  444,  427,  441,  438,  184,  429,  425,  427,
      428,  438,  434,  417,  426,  427,  430,  433,  514,  211,
      217,  218,  225,  514,  221,  514,  141,  214,  246,  267,
      222,  216,  229,  408,  439,  438,  409,  415,  414,  422,
      423,  424,  514,    0,  415,  418,    0,    0,  421,  253,
      407,  419,  414,    0,  413,  414,  121,  400,  410,    0,
      395,  393,  399,  390,  405,  404,  393,  393,  386,  400,
      395,  399,    0,    0,  382,  396,  395,  380,  390,  384,
      391,  386,  371,  373,  374,    0,  379,  376,  384,  374,
      373,  223,  368,  240,  277,  281,  392,  391,  390,  389,

      514,  363,  359,  359,  375,  362,  358,    0,  361,  356,
        0,  373,  352,  351,  383,  349,  350,  355,  357,    0,
        0,  360,  359,    0,  347,  338,  343,    0,    0,    0,
        0,  340,    0,  351,  340,  339,  341,  335,  349,  350,
        0,    0,    0,  347,  346,    0,    0,  335,  342,    0,
      343,    0,  278,  285,  327,  338,  330,  330,  339,  317,
      321,    0,  335,  351,  333,  328,  335,  321,    0,  316,
        0,    0,  313,    0,    0,    0,    0,  314,    0,  317,
      310,    0,  310,  303,    0,    0,  313,  297,  279,    0,
        0,  267,    0,  514,    0,  279,  254,  275,    0,    0,

      255,  254,    0,    0,  258,  267,  270,  264,    0,  220,
      209,  184,    0,  152,    0,    0,  109,    0,   98,    0,
       72,    0,  514,  306,  310,  314,   89,  318,  322,  326,
      330,  334,  338,  342,  346
    } ;

static yyconst short int yy_def[336] =
    {   0,
      323,    1,  324,  324,    1,    1,  323,  323,  323,  323,
      323,  325,  323,  323,  326,  323,  323,  323,  323,  323,
      323,  323,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  323,  323,  323,  325,  323,  323,  328,  323,
      329,  323,  323,  330,  331,  326,  332,  323,  323,  323,
      323,   18,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  323,  333,
      325,  325,  328,  323,  334,  323,  331,  331,  330,  332,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  335,  333,  334,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  333,  335,  323,  323,  323,  323,  327,  327,
      327,  327,  327,  323,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  323,  323,  323,  327,
      327,  327,  327,  323,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,  323,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,    0,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323
    } ;

static yyconst short int yy_nxt[563] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   13,   13,
       13,   16,   17,   13,   18,   19,   13,   20,   21,   22,
        8,    8,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   30,   33,   34,   30,   35,   36,   30,   37,
       38,   39,   40,   30,   41,   30,   42,   43,   47,   58,
       48,   59,   70,   71,   75,   88,   76,   89,  115,   77,
      135,  135,   78,  116,  136,   79,   49,   51,   51,   52,
       51,   51,   51,   51,   53,   51,   51,   51,   51,   54,
       55,   80,   81,   90,   51,   51,   51,   57,   61,   84,
       62,   91,   74,   85,   96,   99,   82,   86,   97,   83,

       92,   63,   64,  100,   98,   65,   87,  102,   60,  101,
       66,  103,  112,  322,  104,  107,   67,   52,  108,  113,
      131,   47,   68,   48,   47,  109,  122,   52,  132,  114,
      110,  111,  124,  321,  320,  125,  153,   55,   55,   49,
      133,  154,  123,   52,  144,  125,   55,   55,   52,   55,
       55,   55,   55,   53,   55,   55,   55,   55,  218,   55,
      145,  125,  219,   55,   55,   55,   57,   51,   51,   52,
       51,   51,   51,   51,  126,   51,   51,   51,   51,   54,
       55,  170,  319,  171,   51,   51,   51,   57,  127,  127,
       52,  127,  127,  127,  127,  128,  127,  127,  127,  127,

       61,  127,   59,  138,  155,  127,  127,  127,  130,  139,
      165,  156,  180,  140,   64,   48,   52,  181,  182,   47,
       47,   48,  195,   52,  318,  166,  167,   47,   55,  122,
      132,  194,  197,  197,  125,  317,  198,   49,   49,  199,
      199,  196,  133,  200,  195,  123,   55,   55,   52,   55,
       55,   55,   55,   53,   55,   55,   55,   55,  250,   55,
      254,  316,  251,   55,   55,   55,   57,  127,  127,   52,
      127,  127,  127,  127,  128,  127,  127,  127,  127,  211,
      127,  195,   48,   52,  127,  127,  127,  130,   55,  195,
      315,  314,  201,  313,  212,  312,  311,  194,  194,  310,

      309,  196,  308,  307,  201,  254,   44,   44,   44,   44,
       46,   46,   46,   46,   56,   56,   56,   56,  121,  121,
      121,  121,   51,   51,   51,   51,   54,   54,   54,   54,
       55,   55,  306,   55,  129,  129,  129,  129,  120,  201,
      120,  120,  127,  127,  127,  127,  253,  305,  253,  253,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  201,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  201,  258,  257,

      256,  255,  201,  200,  200,  198,  198,  252,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  217,  216,
      215,  214,  213,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  136,  136,  201,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  179,  178,  177,  176,
      175,  174,  173,  172,  169,  168,  164,  163,  162,  161,
      160,  159,  158,  157,  152,  151,  150,  149,  148,  147,
      146,  143,  142,  141,  137,  134,   60,  120,  119,  118,

      117,  106,  105,   95,   94,   93,   73,   72,   69,   60,
       50,   45,  323,    7,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323
    } ;

static yyconst short int yy_chk[563] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   12,   16,
       12,   16,   20,   20,   23,   27,   23,   27,   40,   23,
       64,   64,   23,   40,   64,   24,   12,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   24,   25,   28,   15,   15,   15,   15,   18,   26,
       18,   28,  327,   26,   33,   34,   25,   26,   33,   25,

       28,   18,   18,   34,   33,   18,   26,   35,   60,   34,
       18,   35,   39,  321,   35,   38,   18,   55,   38,   39,
       60,   46,   18,   46,   49,   38,   49,   51,   61,   39,
       38,   38,   51,  319,  317,   55,   84,   51,   51,   46,
       61,   84,   49,  127,   75,   51,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,  157,   54,
       75,  127,  157,   54,   54,   54,   54,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   97,  314,   97,   56,   56,   56,   56,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       59,   57,   59,   66,   85,   57,   57,   57,   57,   66,
       94,   85,  107,   66,   59,  120,  128,  107,  107,  121,
      122,  121,  122,  125,  312,   94,   94,  123,  125,  123,
      132,  120,  131,  131,  128,  311,  131,  121,  122,  133,
      133,  125,  132,  133,  194,  123,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  192,  129,
      194,  310,  192,  129,  129,  129,  129,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  150,
      130,  195,  253,  196,  130,  130,  130,  130,  196,  254,
      308,  307,  306,  305,  150,  302,  301,  195,  253,  298,

      297,  196,  296,  292,  289,  254,  324,  324,  324,  324,
      325,  325,  325,  325,  326,  326,  326,  326,  328,  328,
      328,  328,  329,  329,  329,  329,  330,  330,  330,  330,
      331,  331,  288,  331,  332,  332,  332,  332,  333,  287,
      333,  333,  334,  334,  334,  334,  335,  284,  335,  335,
      283,  281,  280,  278,  273,  270,  268,  267,  266,  265,
      264,  263,  261,  260,  259,  258,  257,  256,  255,  251,
      249,  248,  245,  244,  240,  239,  238,  237,  236,  235,
      234,  232,  227,  226,  225,  223,  222,  219,  218,  217,
      216,  215,  214,  213,  212,  210,  209,  207,  206,  205,

      204,  203,  202,  200,  199,  198,  197,  193,  191,  190,
      189,  188,  187,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  159,  158,  156,  155,
      153,  152,  151,  149,  146,  145,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  106,  105,  104,  103,
      101,  100,   99,   98,   96,   95,   93,   92,   91,   90,
       89,   88,   87,   86,   83,   82,   81,   79,   78,   77,
       76,   70,   68,   67,   65,   63,   58,   48,   43,   42,

       41,   37,   36,   32,   31,   29,   22,   21,   19,   17,
       14,   11,    7,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fl.l"
#define INITIAL 0
/*
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
#line 17 "fl.l"
#include "bison.tab.h"
#include "atof.h"

#ifdef _WIN64
#define atoll(S) _atoi64(S)
#else
#include <unistd.h>
#endif

void yyerror(char *s, ...);
#define YY_NEVER_INTERACTIVE 1
#define YY_NO_UNISTD_H

#define YY_NEVER_INTERACTIVE 1
#define COMMENT 1

#define BTWMODE 2

#line 686 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 36 "fl.l"


#line 840 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 324 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 514 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 38 "fl.l"
{return AND; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "fl.l"
{return OR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "fl.l"
{ return LOAD; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "fl.l"
{ return FILTER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "fl.l"
{ return DESC; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "fl.l"
{ return ASC; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "fl.l"
{ return ORDER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "fl.l"
{ return BY; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "fl.l"
{ return JOIN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "fl.l"
{ return STORE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "fl.l"
{ return INTO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "fl.l"
{ return GROUP; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "fl.l"
{ return AS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "fl.l"
{ return SELECT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "fl.l"
{ return USING; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "fl.l"
{ return COUNT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "fl.l"
{ return SUM; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "fl.l"
{ return AVG; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "fl.l"
{ return MIN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "fl.l"
{ return MAX; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "fl.l"
{ return LIMIT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "fl.l"
{ return ON; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "fl.l"
{ return BINARY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "fl.l"
{ return DISTINCT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "fl.l"
{ return LEFT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "fl.l"
{ return RIGHT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "fl.l"
{ return OUTER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "fl.l"
{ return SEMI; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "fl.l"
{ return ANTI; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "fl.l"
{return SORT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "fl.l"
{return SEGMENTS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "fl.l"
{return PRESORTED; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "fl.l"
{return INSERT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "fl.l"
{return WHERE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "fl.l"
{return DISPLAY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "fl.l"
{return CASE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "fl.l"
{return WHEN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "fl.l"
{return THEN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 76 "fl.l"
{return ELSE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 77 "fl.l"
{return END; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 78 "fl.l"
{return SHOW; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 79 "fl.l"
{return TABLES; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 80 "fl.l"
{return TABLE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 81 "fl.l"
{return DESCRIBE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "fl.l"
{return DROP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "fl.l"
{return DELETE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 84 "fl.l"
{return FROM; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 85 "fl.l"
{return LIKE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 86 "fl.l"
{return CREATE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "fl.l"
{return INDEX; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 88 "fl.l"
{return YEAR; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 89 "fl.l"
{return MONTH; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 90 "fl.l"
{return DAY; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "fl.l"
{return CAST_TO_INT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "fl.l"
{return APPEND; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "fl.l"
{ yylval.intval = atoll(yytext);  return INTNUM; }
	YY_BREAK
case 57:
#line 96 "fl.l"
case 58:
#line 97 "fl.l"
case 59:
YY_RULE_SETUP
#line 97 "fl.l"
{ yylval.strval = strdup(yytext); return DECIMAL1; }
	YY_BREAK
case 60:
#line 99 "fl.l"
case 61:
#line 100 "fl.l"
case 62:
YY_RULE_SETUP
#line 100 "fl.l"
{ yylval.floatval = atoff(yytext) ;return APPROXNUM; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "fl.l"
{ yylval.strval = strdup(yytext); return STRING; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "fl.l"
{ yylval.strval = strdup(yytext); return STRING;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "fl.l"
{ yylval.intval = 1; return BOOL1; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "fl.l"
{ yylval.intval = -1; return BOOL1; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "fl.l"
{ yylval.intval = 0; return BOOL1; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "fl.l"
{ yylval.strval = strdup(yytext); return STRING; }
	YY_BREAK
case 69:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 109 "fl.l"
{ yyerror("Unterminated string %s", yytext); break;}
	YY_BREAK
case 70:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 110 "fl.l"
{ yyerror("Unterminated string %s", yytext); break;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "fl.l"
{ return yytext[0]; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "fl.l"
{ return AND; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "fl.l"
{ return OR; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "fl.l"
{ return ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 117 "fl.l"
{ return EQUAL; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "fl.l"
{ return NONEQUAL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 119 "fl.l"
{ yylval.subtok = 4; return COMPARISON; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 120 "fl.l"
{ yylval.subtok = 12; return COMPARISON; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 121 "fl.l"
{ yylval.subtok = 6; return COMPARISON; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 122 "fl.l"
{ yylval.subtok = 2; return COMPARISON; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 123 "fl.l"
{ yylval.subtok = 5; return COMPARISON; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 124 "fl.l"
{ yylval.subtok = 1; return COMPARISON; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 125 "fl.l"
{ yylval.subtok = 3; return COMPARISON; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "fl.l"
{ yylval.strval = strdup(yytext+1);
yylval.strval[yyleng-2] = 0; return FILENAME; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 130 "fl.l"
{ yylval.strval = strdup(yytext);return NAME; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 131 "fl.l"
{ yylval.strval = strdup(yytext+1);yylval.strval[yyleng-2] = 0; return FILENAME; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 134 "fl.l"

	YY_BREAK
case 88:
YY_RULE_SETUP
#line 135 "fl.l"
{  }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 136 "fl.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1371 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(BTWMODE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 324 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 324 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 323);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 136 "fl.l"


void PROC_FLUSH_BUF ( FILE * xFile )
{
        yy_delete_buffer ( YY_CURRENT_BUFFER );
        yy_switch_to_buffer ( yy_create_buffer ( xFile, YY_BUF_SIZE ) ); 
}



